# Generated by Django 4.2.7 on 2026-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_fcaba7_idx',
            old_name='expenses_ex_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_date_2850f8_idx',
            old_name='expenses_ex_date_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in currency (e.g., ₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key for idempotent operations', max_length=255, null=True, unique=True),
        ),
    ]
